---
title: "Project2"
output: html_document
date: '2022-08-09'
---
```{r}
Data <- read.csv('kc_house_data.csv')
Data
```

```{r}
library(ggplot2)
set.seed(1)
sample<-sample.int(nrow(Data), floor(.5*nrow(Data))) # 50/50 split
train<-Data[sample, ] # training data frame
test<-Data[-sample, ] # test data frame
```


```{r}
# install.packages('tidyverse')
library(dplyr)
train %>%
        group_by(waterfront) %>%
        tally()

```
```{r}
# price vs. bedrooms
library(tidyverse)
ggplot(train, aes(x=price,y=bedrooms))+
geom_point()+
ylim(0, 15)
```

```{r}
#view score vs zipcode
train<-train%>%
mutate(viewRating=ifelse(view<2,"Bad","Good"))
mytab2<-table(train$zipcode, train$viewRating)
mytab2
```
```{r}
head(train)
```


```{r}
ggplot(train, aes(x=grade, fill=viewRating))+
geom_bar(position = "stack")+
labs(x="Grade", y="Count", title="View Ratings by Grade")
```

```{r}
# view score v latitude
ggplot(train, aes(x=lat, y=viewz))+
geom_boxplot(fill="Blue")+
labs(x="Latitude", y="View Score",
title="Dist of View Score by Latitude")
```

```{r}
Data<-Data%>%
mutate(grade=ifelse(grade<6,"Bad","Good"))
mytab2<-table(Data$waterfront, Data$grade)
mytab2
```
```{r}
# sqft lot vs sqft living by price and grade score
# Data <- read.csv('kc_house_data.csv')
ggplot(Data, aes(x=sqft_lot, y=grade, color = viewz))+
geom_point()+
  scale_size(range = c(0.1,12))
```

```{r}
ggplot(Data, aes(x=as.factor(grade)))+
geom_bar()+
labs(x='Grade', y='Count', title="Grade Score Distribution")
```

```{r}
library(tidyverse)
ggplot(Data, aes(x=price, y=sqft_lot,fill=grade))+
geom_point(shape=21, alpha=0.5)+
scale_size(range = c(0.1,12))+
labs(x="GDP", y="Life Exp", title="Scatterplot of Price against Sqft Lot by Grade")
```

```{r}
priceViews <- table(Data$price, Data$grade)
barplot(priceViews)
```


```{r}
split(train, cut(train$anim, 3))
```

